travis:
  secure:
    BINSTAR_TOKEN: Kae5PSAS7ZyLKmaOvZtKFxvL670D5J6PY1MQ58G7kvyW/kcln+81Ln0Y9ApsUtNHMtKrTCHZQDidxcnhezF3IQ1Xwajav/tvf3gKFy0n12BUVaMJ1+8mlr7HOsr/Cd2pZC6fckgy8VrS8tOjK2UkcYOCMVF9G4EqYJ3Ew1gd5LB1EW99h3I0FEftmccV52505cDn5wUbiAJl8MGyvjvz+s/FlM+e+AcKxRe4UGRUOQjGO3tfOJGxxPcuuVd1pGeDQjV5/25cMCzpGZ2HE/ogrggUC4mEluc7YNpNFeQLHh3c1mWPQpPvYEAOqnms/kZQO1YQqy1iOCCRL/Gn0Mx74BJviE3rJNphBvmsJsJakxPw+fLVZntQ9wq2QPjfNHAyIteJekcV07EWpjoKpXgJ/5MglJ2MS7bAFKn/ZQOc8isKbwnFqRgXldHhB72G1RoJtEMi8tpPNZuSuzakea3aXwoAVxAYIfOswMWjoREcl94Mb8KoJdO0V+iObzwNa4gkKEBkTgf5YZEVj7F/Db0kv93JlKeBI565vM5vZRzOq3TjhW/jXEAR+87LNayb11qcmyikcLWxftSdKKeFI0rbtucS1bJZh+dth2H3QFPMLY3aObTu6aDN3IlovjS2wtpetHgTwNjKS+lpEZbgCIzTIznA5uEXj0yCiUtDV0NXIng=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
