c_compiler_version:        # [linux and not aarch64]
  - 8                      # [linux and not (s390x or aarch64 or ppc64le)]
  - 8                      # [linux and ppc64le]
  - 8                      # [linux and s390x]
cxx_compiler_version:      # [linux]
  - 8                      # [linux and not (s390x or aarch64 or ppc64le)]
  - 8                      # [linux and ppc64le]
  - 8                      # [linux and s390x]
