travis:
  secure:
    BINSTAR_TOKEN: Vg+FDRbnqx2AjfRjDslR7+y3gv3K/Mib81GvrrjAYAIyxWEtuClkg4jQrWZanMoEmOOTsLFB+W/x2q3JcdSTuqxmrHTsXFdjwAewjxKGXlfPYFxRGrR95cySnCWaSBsyUUC+/ek0pTgq28TTzRxp3ncSjn6+wp/fJHrOH699UYdvE+7T+0R3QCpQQcy0N5XGFqnQ+a+HDnl3J/0gHjwFU5IYbacwLTW6dzToxNm/+VkOXAv5fhiS8QK9K+WkOORXtmrmPh6S879FsrOLTAY70MCcfSwCp6U2EIa2fVzFnK1FPqkwFjLSDsGvQjF3IRPOE+Ng7N/AP3zaMq2lIucucmCTQQpPBMpI8zUZoXJ8VowHTDzwLTM9HbUL0hkG699lqQrf1i1p0h0dqQ8N5hU3BVjXkSqOPBiiNY8nWKVSKjCDSgAkzVzVCCu3jDWJqq2PtTK0fpMk3VkfJYnTRjTrgmlPdeLrgcN2/fqZUmyHNOKrFm61OlaCPG2y9jPVJyy5njkUODnjjkBJGBeCYBgCzqySK4YypNLH8rV4csxtVmtObIYo9xgD4PhpAjdGeDU9gmxBpTTua1zLrTg4G619BTl+nGpGZ1wH+2oLQbLvNpBBdxgS7HiJ7Y35zCraUDE1s4RvMd0z4l2S2gPPPHgo+vNHKFJu2NZQGPL8UZtS6GY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
