name: "Checks"

# Run integrity checks on the monorepo structure

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  make-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run make checks
        run: |
          make checks